### ISSUE TITLE
Tarea del módulo 1.1

### ISSUE THREAD

**Issue by MMMatus** [SistemasTecTlaxiaco/CursoGitHubMorgan#1]
Creando una incidencia para tareas y subir evidencias sobre una actividad, puede ser un Link captura de pantalla, etc.

**Comment by MMMatus** [comment]
¿Por qué querrías usar GitHub en el aula de clases?

Para la gestión de las actividades de los estudiantes como, tareas, proyectos y demás.

**Comment by josealfredo79** [comment]
Bien hecho la primera actividad 1.1
