### ISSUE TITLE
Módulo 3.4 Asignación

### ISSUE THREAD

**Issue by MMMatus** [SistemasTecTlaxiaco/CursoGitHubMorgan#14]
![image](https://github.com/user-attachments/assets/d802c496-a65d-44ff-b80c-f48f04ecc933)
![image](https://github.com/user-attachments/assets/da5bf691-c89d-4972-9a94-afe56e23f213)

[**Enlace de la Actividad:** ](https://classroom.github.com/a/VDc2XWgt)  `https://classroom.github.com/a/VDc2XWgt`

![image](https://github.com/user-attachments/assets/0e85fe90-8edb-4821-89f6-ee12d58182b0)

![image](https://github.com/user-attachments/assets/118395d9-9ecb-4e54-a94e-102134f88056)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...la actividad 3.4
